all:
  vars:
    ansible_user: vagrant

  children:
    # Gruppo globale per tutte le VM
    docker_nodes:
      hosts:
        monitoring-prometheus:
          ansible_host: 192.168.56.10
          ansible_ssh_private_key_file: "/Users/mariusdumitru/Desktop/repos/MonitoringStack/vagrant_env/.vagrant/machines/monitoring-prometheus/virtualbox/private_key"
        monitoring-grafana:
          ansible_host: 192.168.56.11
          ansible_ssh_private_key_file: "/Users/mariusdumitru/Desktop/repos/MonitoringStack/vagrant_env/.vagrant/machines/monitoring-grafana/virtualbox/private_key"
        elasticsearch-host:
          ansible_host: 192.168.56.12
          ansible_ssh_private_key_file: "/Users/mariusdumitru/Desktop/repos/MonitoringStack/vagrant_env/.vagrant/machines/elasticsearch-host/virtualbox/private_key"

    # Gruppi dinamici per le singole macchine
    monitoring-prometheus_group:
      hosts:
        monitoring-prometheus:
    monitoring-grafana_group:
      hosts:
        monitoring-grafana:
    elasticsearch-host_group:
      hosts:
        elasticsearch-host:
