# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "monitoring-prometheus" do |node|
    node.vm.box = "generic/rocky9"
    node.vm.hostname = "monitoring-prometheus"
        node.vm.network "private_network", ip: "192.168.56.10"
        
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
  config.vm.define "monitoring-grafana" do |node|
    node.vm.box = "generic/rocky9"
    node.vm.hostname = "monitoring-grafana"
        node.vm.network "private_network", ip: "192.168.56.11"
        
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
  config.vm.define "elasticsearch-host" do |node|
    node.vm.box = "generic/rocky9"
    node.vm.hostname = "elasticsearch-host"
        node.vm.network "private_network", ip: "192.168.56.12"
        
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

end